#spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2
#  datasource:
#    url: jdbc:h2:mem:test
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: {AWS RDS Endpoint}
    username: {RDS Mysql Admin id}
    password: {RDS Mysql Admin password}
  jpa:
    hibernate:
      ddl-auto: create  # (1) ??? ?? ??
    show-sql: true      # (2) SQL ?? ??
    properties:
      hibernate:
        format_sql: true  # (3) SQL pretty print

  redis:
    host: localhost
    port: 6379

jwt.secret: { jwt secret }

jwt:
  key: { jwt key }
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420

mail:
  address:
    admin: { admin email }

