
spring:
  config:
#    activate:
#      on-profile: prod1
    import: aws-parameterstore:/project-todo-community/hsj
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: create  # (1) ??? ?? ??
    show-sql: true      # (2) SQL ?? ??
    properties:
      hibernate:
        format_sql: true  # (3) SQL pretty print
    database-platform: org.hibernate.dialect.MySQL8Dialect

  redis:
    host: localhost
    port: 6379


aws:
  paramstore:
    enabled: true
    prefix: /project-todo-community
    profile-separator: _
    name: hsj

jwt.secret: uyioio3ljknklgy2uijhj5klovwg5yujah2khui3kjhui

jwt:
  key: uyioio3ljknklgy2uijhj5klovwg5yujah2khui3kjhui
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 720

mail:
  smtp:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    auth: true
    starttls:
      enable: true
  subject:
    member:
      registration: 인증 번호 발송
  address:
    admin:

cloud:
  aws:
    credentials:
      accessKey: { AWS accessKey }  # AWS IAM AccessKey 적기
      secretKey: { AWS secretKey } # AWS IAM SecretKey 적기
    region:
      static: "ap-northeast-2"
    stack:
      auto: false

management:
  endpoints:
    web:
      base-path: /actuator
      path-mapping:
        health: health
      exposure:
        include: "*"
