#spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2
#  datasource:
#    url: jdbc:h2:mem:test



spring:
  config:
    import: aws-parameterstore:/project-todo-community/hsj
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: create  # (1) ??? ?? ??
    show-sql: true      # (2) SQL ?? ??
    properties:
      hibernate:
        format_sql: true  # (3) SQL pretty print

  redis:
    host: localhost
    port: 6379


aws:
  paramstore:
    enabled: true
    prefix: /project-todo-community
    profile-separator: _
    name: hsj



jwt.secret:



jwt:
  key: uyioio3ljknklgy2uijhj5klovwg5yujah2khui3kjhui
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420

mail:
  address:
    admin: hsj99215@gmail.com

cloud:
  aws:
    credentials:
      accessKey: { AWS accessKey }  # AWS IAM AccessKey 적기
      secretKey: { AWS secretKey } # AWS IAM SecretKey 적기
    region:
      static: "ap-northeast-2"
    stack:
      auto: false

